model:
  name: 'osnet_x0_25'
  pretrained: True

data:
  type: 'image'
  sources:
    - market1501
    - cuhk03
    - dukemtmcreid
    - lpw
  targets:
    - sensereid
    - market1501
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/osnet_x0_25_pro'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.003
  max_epoch: 180
  batch_size: 128
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 'cosine'

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False
